LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := privapp-permissions-helium314.keyboard.xml
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_PRODUCT_MODULE := true
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT_ETC)/permissions
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := HeliBoard
LOCAL_OVERRIDES_PACKAGES := LatinIME
LOCAL_SRC_FILES := HeliBoard.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRODUCT_MODULE := true
LOCAL_PRIVILEGED_MODULE := true
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_REPLACE_PREBUILT_APK_INSTALLED := $(LOCAL_PATH)/$(LOCAL_MODULE).apk
LOCAL_REQUIRED_MODULES := privapp-permissions-helium314.keyboard.xml
LOCAL_DEX_PREOPT := false
$(shell mkdir -p $(TARGET_OUT_PRODUCT)/priv-app/$(LOCAL_MODULE)/lib/$(TARGET_ARCH))
$(shell unzip -qqjo $(LOCAL_PATH)/$(LOCAL_MODULE).apk lib/arm64-v8a/*.so -d $(TARGET_OUT_PRODUCT)/priv-app/$(LOCAL_MODULE)/lib/$(TARGET_ARCH))
include $(BUILD_PREBUILT)
